#!/usr/bin/env bash

if ! which black &>/dev/null; then
    echo "Black is required to format this project"
    exit 1
fi

echo "Formatting..."
black --safe --exclude api-daemon/migrations .
ret=$?
if [[ $ret -eq 0 ]]; then
    echo "Successfully formatted project!"
fi
exit $ret
