#!/usr/bin/env bash

if ! which black &>/dev/null; then
    echo "Black is required to format this project"
    exit 1
fi

if [[ $1 == "check" ]]; then
    check="--check"
fi

pushd $( git rev-parse --show-toplevel ) &>/dev/null

echo ">>> Formatting..."
black --safe ${check} --exclude api-daemon/migrations .
ret=$?
if [[ $ret -eq 0 ]]; then
    echo "Successfully formatted project!"
fi

popd &>/dev/null
exit $ret
