#!/usr/bin/env bash

if ! which flake8 &>/dev/null; then
    echo "Flake8 is required to lint this project"
    exit 1
fi

echo "Linting..."
flake8
ret=$?
if [[ $ret -eq 0 ]]; then
    echo "No linting issues found!"
fi
exit $ret
