#!/usr/bin/env bash

if ! which flake8 &>/dev/null; then
    echo "Flake8 is required to lint this project"
    exit 1
fi

flake8 \
    --ignore=E501 \
    --exclude=api-daemon/migrations/versions,api-daemon/provisioner/examples
ret=$?
if [[ $ret -eq 0 ]]; then
    echo "No linting issues found!"
fi
exit $ret
