Content-Type: text/cloud-config; charset="us-ascii"
MIME-Version: 1.0

#cloud-config
# Example user-data file. It will:
#  1. Generate locales for us
#  2. Update packages and install OpenSSH and sudo
#  3. Disable the manually-enabled cloud-init target (see debootstrap_script.py)
#  4. Reboot the system
# You can, of course, do anything you want in here which cloud-init normally supports.
bootcmd:
  - "locale-gen"
package_update: true
packages:
  - openssh-server
  - sudo
runcmd:
  - "systemctl disable cloud-init.target"
  - "reboot"
