"""PVC version 0.7

Revision ID: 3bc6117ea44d
Revises: 88c8514684f7
Create Date: 2020-08-24 14:34:36.919308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc6117ea44d'
down_revision = '88c8514684f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_benchmarks')
    # ### end Alembic commands ###
