"""PVC version 0.9.0

Revision ID: 3efe890e1d87
Revises: 3bc6117ea44d
Create Date: 2020-10-29 11:49:58.756626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efe890e1d87'
down_revision = '3bc6117ea44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_template', sa.Column('migration_method', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_template', 'migration_method')
    # ### end Alembic commands ###
