"""PVC version 0.9.37

Revision ID: 5c2109dbbeae
Revises: bae4d5a77c74
Create Date: 2021-10-02 00:47:29.693579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2109dbbeae'
down_revision = 'bae4d5a77c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_benchmarks', sa.Column('test_format', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage_benchmarks', 'test_format')
    # ### end Alembic commands ###
