"""PVC version 0.9.55

Revision ID: 88fa0d88a9f8
Revises: 5c2109dbbeae
Create Date: 2022-10-06 10:33:38.784497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fa0d88a9f8'
down_revision = '5c2109dbbeae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'script',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profile', 'system_template',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'system_template',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profile', 'script',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
