"""PVC version 0.9.18

Revision ID: bae4d5a77c74
Revises: 3efe890e1d87
Create Date: 2021-06-02 15:41:40.061806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae4d5a77c74'
down_revision = '3efe890e1d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE network ALTER COLUMN vni TYPE TEXT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE network ALTER COLUMN vni TYPE INTEGER USING vni::integer')
    # ### end Alembic commands ###
