{
 "title": "PVC Cluster Overview",
 "tags": [ "pvc" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_info{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_nodes{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_osds{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Faults",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pvc_cluster_faults{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Health",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_cluster_health{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Health History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pvc_cluster_health{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Primary Node",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_info{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active VMs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_states{cluster=\"$cluster\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_pools{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maintenance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_cluster_maintenance{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inactive VMs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_states{cluster=\"$cluster\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_volumes{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Health",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_node_health{cluster=\"$cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Health History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pvc_node_health{cluster=\"$cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_info{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Networks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_networks{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_snapshots{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster States",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Daemon States",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pvc_nodes{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "pvc_node_daemon_states{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node Domain States",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pvc_nodes{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "pvc_node_domain_states{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VM States",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pvc_vms{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "pvc_vm_states{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OSD States",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pvc_osds{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "pvc_ceph_osd_up_states{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "pvc_ceph_osd_in_states{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Overall Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "gauge",
     "description": "Total CPU utilization of the cluster (n-1)",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_cluster_cpu_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Utilization History",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_cluster_cpu_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Utilization",
     "type": "gauge",
     "description": "Total Network utilization of the cluster (all active interfaces on all active nodes)",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_cluster_network_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Utilization History",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_cluster_network_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VM Disk Space Utilization",
     "type": "gauge",
     "description": "Total Disk space utilization of the cluster (n-2 for copies=3)",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_cluster_disk_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VM Disk Space Utilization History",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_cluster_disk_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Actual Memory Utilization",
     "type": "gauge",
     "description": "Total real memory utilization of the cluster (n-1)",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_cluster_memory_real_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Actual Memory Utilization History",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_cluster_memory_real_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocated Memory Utilization",
     "type": "gauge",
     "description": "Total allocated (running VMs) memory utilization of the cluster (n-1)",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_cluster_memory_allocated_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocated Memory Utilization History",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_cluster_memory_allocated_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Provisioned Memory Utilization",
     "type": "gauge",
     "description": "Total provisioned (all VMs) memory utilization of the cluster (n-1)",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_cluster_memory_provisioned_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Provisioned Memory Utilization History",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_cluster_memory_provisioned_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Per-Node Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "gauge",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_node_cpu_utilization{cluster=\"$cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CPU Utilization History",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 9, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_node_cpu_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Load Average History",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 11, "x": 13, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pvc_node_load_average{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Utilization",
     "type": "gauge",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_node_network_utilization{cluster=\"$cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Network Utilization History",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 9, "x": 4, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_node_network_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Traffic History",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 11, "x": 13, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "pvc_node_network_traffic_rx{cluster=\"$cluster\"}",
       "legendFormat": "{{node}} RX"
      },
      {
       "expr": "pvc_node_network_traffic_tx{cluster=\"$cluster\"}",
       "legendFormat": "{{node}} TX"
      }
     ]
    },
    {
     "title": "Actual Memory Utilization",
     "type": "gauge",
     "description": "Real memory utilization of each node",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_node_used_memory_utilization{cluster=\"$cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Actual Memory Utilization History",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 9, "x": 4, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_node_used_memory_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Actual Memory History",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 11, "x": 13, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "pvc_node_used_memory{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocated Memory Utilization",
     "type": "gauge",
     "description": "Allocated (running VMs) memory utilization of each node",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_node_allocated_memory_utilization{cluster=\"$cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Allocated Memory Utilization History",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 9, "x": 4, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_node_allocated_memory_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocated Memory History",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 11, "x": 13, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "pvc_node_allocated_memory{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Provisioned Memory Utilization",
     "type": "gauge",
     "description": "Provisioned (all VMs) memory utilization of each node",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_node_provisioned_memory_utilization{cluster=\"$cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Provisioned Memory Utilization History",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 9, "x": 4, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_node_provisioned_memory_utilization{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Provisioned Memory History",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 11, "x": 13, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "pvc_node_provisioned_memory{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Pool Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool Disk Space Utilization",
     "type": "gauge",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_ceph_pool_used_percent{cluster=\"$cluster\"}",
       "legendFormat": "Pool {{pool}}"
      }
     ]
    },
    {
     "title": "Pool Disk Space Utilization History",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 16, "x": 8, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_ceph_pool_used_percent{cluster=\"$cluster\"}",
       "legendFormat": "Pool {{pool}}"
      }
     ]
    },
    {
     "title": "Pool Objects History",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pvc_ceph_pool_num_objects{cluster=\"$cluster\"}",
       "legendFormat": "Pool {{pool}} # Unique Objects"
      },
      {
       "expr": "pvc_ceph_pool_num_objects_copies{cluster=\"$cluster\"}",
       "legendFormat": "Pool {{pool}} # Total Copies"
      },
      {
       "expr": "pvc_ceph_pool_num_objects_clones{cluster=\"$cluster\"}",
       "legendFormat": "Pool {{pool}} # Clones"
      },
      {
       "expr": "pvc_ceph_pool_num_objects_missing_on_primary{cluster=\"$cluster\"}",
       "legendFormat": "Pool {{pool}} # Missing on Primary"
      },
      {
       "expr": "pvc_ceph_pool_num_objects_unfound{cluster=\"$cluster\"}",
       "legendFormat": "Pool {{pool}} # Unfound"
      },
      {
       "expr": "pvc_ceph_pool_num_objects_degraded{cluster=\"$cluster\"}",
       "legendFormat": "Pool {{pool}} # Degraded"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage OSD Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSD Disk Space Utilization",
     "type": "gauge",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_ceph_osd_util{cluster=\"$cluster\"}",
       "legendFormat": "OSD {{osd}}"
      }
     ]
    },
    {
     "title": "OSD Disk Space Utilization History",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 16, "x": 8, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_ceph_osd_util{cluster=\"$cluster\"}",
       "legendFormat": "OSD {{osd}}"
      }
     ]
    },
    {
     "title": "Ceph OSD IOPS (+ Read/- Write)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pvc_ceph_osd_rd_ops{cluster=\"$cluster\"}",
       "legendFormat": "OSD {{osd}} Read"
      },
      {
       "expr": "pvc_ceph_osd_wr_ops{cluster=\"$cluster\"}",
       "legendFormat": "OSD {{osd}} Write"
      }
     ]
    },
    {
     "title": "Ceph OSD Data Rate (+ Read/- Write)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "pvc_ceph_osd_rd_data{cluster=\"$cluster\"}",
       "legendFormat": "OSD {{osd}} Read"
      },
      {
       "expr": "pvc_ceph_osd_wr_data{cluster=\"$cluster\"}",
       "legendFormat": "OSD {{osd}} Write"
      }
     ]
    }
   ]
  }
 ]
}