{
 "title": "PVC Cluster",
 "tags": [ "pvc" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Cluster", "query": { "query": "label_values(pvc_cluster_name)" } },
   {
    "name": "cluster_id",
    "query": {
     "query": "label_values({pvc_cluster_name=\"$cluster_name\"},pvc_cluster_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "Cluster ID as provided by PVC.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_info{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maintenance",
   "type": "stat",
   "description": "Cluster maintenance status.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_cluster_maintenance{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Faults",
   "type": "table",
   "description": "List of faults in the cluster.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pvc_cluster_faults{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Health",
   "type": "gauge",
   "description": "Current health percentage of the cluster.",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_cluster_health{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Health History",
   "type": "timeseries",
   "description": "Health percentage history of the cluster.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pvc_cluster_health{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Primary Node",
   "type": "stat",
   "description": "Current primary coordinator node.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_info{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Current primary coordinator PVC version.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_info{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Total nodes in the cluster.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_nodes{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active VMs",
   "type": "stat",
   "description": "Total active VMs in the cluster (state is \"start\", \"restart\", \"migrate\", or \"unmigrate\").",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_states{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "stat",
   "description": "Total storage OSDs in the cluster.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_osds{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "stat",
   "description": "Total storage volumes (VM disks) in the cluster.",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_volumes{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Health",
   "type": "gauge",
   "description": "Current health percentage of each node in the cluster.",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_node_health{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Health History",
   "type": "timeseries",
   "description": "Health percentage history of each node in the cluster.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pvc_node_health{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Networks",
   "type": "stat",
   "description": "Total PVC-managed networks in the cluster.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_networks{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inactive VMs",
   "type": "stat",
   "description": "Total inactive VMs in the cluster (state is \"disable\", \"shutdown\", \"stop\", \"provision\", or \"fail\").",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_states{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "description": "Total storage pools in the cluster.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_pools{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "stat",
   "description": "Total storage volume snapshots in the cluster.",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_snapshots{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster States",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Daemon States",
     "type": "timeseries",
     "description": "PVC Node Daemon state history of each node.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pvc_nodes{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "pvc_node_daemon_states{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node Domain States",
     "type": "timeseries",
     "description": "Domain state history of each node.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pvc_nodes{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "pvc_node_domain_states{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VM States",
     "type": "timeseries",
     "description": "History count of VMs in each VM state.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pvc_vms{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "pvc_vm_states{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OSD States",
     "type": "timeseries",
     "description": "History count of OSDs in each OSD state.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pvc_osds{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "pvc_ceph_osd_up_states{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "pvc_ceph_osd_in_states{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Overall Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "gauge",
     "description": "Current total CPU utilization of the cluster (n-1).",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_cluster_cpu_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Utilization History",
     "type": "timeseries",
     "description": "Total CPU utilization history of the cluster (n-1).",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_cluster_cpu_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Utilization",
     "type": "gauge",
     "description": "Current total Network utilization of the cluster (all active interfaces on all active nodes, full-duplex).",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_cluster_network_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Utilization History",
     "type": "timeseries",
     "description": "Total Network utilization history of the cluster (all active interfaces on all active nodes, full-duplex).",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_cluster_network_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VM Disk Space Utilization",
     "type": "gauge",
     "description": "Current total VM disk space utilization of the cluster (n-2 for copies=3).",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_cluster_disk_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VM Disk Space Utilization History",
     "type": "timeseries",
     "description": "Total VM disk space utilization history of the cluster (n-2 for copies=3).",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_cluster_disk_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Actual Memory Utilization",
     "type": "gauge",
     "description": "Current total real memory utilization of the cluster (n-1).",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_cluster_memory_real_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Actual Memory Utilization History",
     "type": "timeseries",
     "description": "Total real memory utilization history of the cluster (n-1).",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_cluster_memory_real_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocated Memory Utilization",
     "type": "gauge",
     "description": "Current total allocated (active VMs) memory utilization of the cluster (n-1).",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_cluster_memory_allocated_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocated Memory Utilization History",
     "type": "timeseries",
     "description": "Total allocated (active VMs) memory utilization history of the cluster (n-1).",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_cluster_memory_allocated_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Provisioned Memory Utilization",
     "type": "gauge",
     "description": "Current total provisioned (all VMs) memory utilization of the cluster (n-1).",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_cluster_memory_provisioned_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Provisioned Memory Utilization History",
     "type": "timeseries",
     "description": "Total provisioned (all VMs) memory utilization history of the cluster (n-1).",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_cluster_memory_provisioned_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "gauge",
     "description": "Current CPU utilization of each node.",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_node_cpu_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CPU Utilization History",
     "type": "timeseries",
     "description": "CPU utilization history of each node.",
     "gridPos": { "h": 13, "w": 9, "x": 4, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_node_cpu_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Load Average History",
     "type": "timeseries",
     "description": "CPU load average history of each node (source metric).",
     "gridPos": { "h": 13, "w": 11, "x": 13, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pvc_node_load_average{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Utilization",
     "type": "gauge",
     "description": "Current network utilization of each node (total of all active interfaces, full-duplex).",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_node_network_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Network Utilization History",
     "type": "timeseries",
     "description": "Network utilization history of each node (total of all active interfaces, full-duplex).",
     "gridPos": { "h": 13, "w": 9, "x": 4, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_node_network_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Traffic History (+ RX/- TX)",
     "type": "timeseries",
     "description": "Network traffic history of each node (source metric, total of all active interfaces).",
     "gridPos": { "h": 13, "w": 11, "x": 13, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "pvc_node_network_traffic_rx{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "{{node}} RX"
      },
      {
       "expr": "pvc_node_network_traffic_tx{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "{{node}} TX"
      }
     ]
    },
    {
     "title": "Actual Memory Utilization",
     "type": "gauge",
     "description": "Current real memory utilization of each node.",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_node_used_memory_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Actual Memory Utilization History",
     "type": "timeseries",
     "description": "Real memory utilization history of each node.",
     "gridPos": { "h": 13, "w": 9, "x": 4, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_node_used_memory_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Actual Memory History",
     "type": "timeseries",
     "description": "Real memory history of each node (source metric).",
     "gridPos": { "h": 13, "w": 11, "x": 13, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "pvc_node_used_memory{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocated Memory Utilization",
     "type": "gauge",
     "description": "Current allocated (active VMs) memory utilization of each node.",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_node_allocated_memory_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Allocated Memory Utilization History",
     "type": "timeseries",
     "description": "Allocated (active VMs) memory utilization history of each node.",
     "gridPos": { "h": 13, "w": 9, "x": 4, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_node_allocated_memory_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocated Memory History",
     "type": "timeseries",
     "description": "Allocated (active VMs) memory history of each node (source metric).",
     "gridPos": { "h": 13, "w": 11, "x": 13, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "pvc_node_allocated_memory{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Provisioned Memory Utilization",
     "type": "gauge",
     "description": "Current provisioned (all VMs) memory utilization of each node.",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_node_provisioned_memory_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Provisioned Memory Utilization History",
     "type": "timeseries",
     "description": "Provisioned (all VMs) memory utilization history of each node.",
     "gridPos": { "h": 13, "w": 9, "x": 4, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_node_provisioned_memory_utilization{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Provisioned Memory History",
     "type": "timeseries",
     "description": "Provisioned (all VMs) memory history of each node (source metric).",
     "gridPos": { "h": 13, "w": 11, "x": 13, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "pvc_node_provisioned_memory{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Pool Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool Disk Space Utilization",
     "type": "gauge",
     "description": "Current disk space utilization of each Ceph pool.",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_ceph_pool_used_percent{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "Pool {{pool}}"
      }
     ]
    },
    {
     "title": "Pool Disk Space Utilization History",
     "type": "timeseries",
     "description": "Disk space utilization history of each Ceph pool.",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_ceph_pool_used_percent{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "Pool {{pool}}"
      }
     ]
    },
    {
     "title": "Pool Disk Space History",
     "type": "timeseries",
     "description": "Disk space history of each Ceph pool (source metric).",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "pvc_ceph_pool_used_bytes{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "Pool {{pool}}"
      }
     ]
    },
    {
     "title": "Pool Objects History",
     "type": "timeseries",
     "description": "Object count history of each Ceph pool.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pvc_ceph_pool_num_objects{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "Pool {{pool}} # Unique Objects"
      },
      {
       "expr": "pvc_ceph_pool_num_objects_copies{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "Pool {{pool}} # Total Copies"
      },
      {
       "expr": "pvc_ceph_pool_num_objects_clones{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "Pool {{pool}} # Clones"
      },
      {
       "expr": "pvc_ceph_pool_num_objects_missing_on_primary{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "Pool {{pool}} # Missing on Primary"
      },
      {
       "expr": "pvc_ceph_pool_num_objects_unfound{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "Pool {{pool}} # Unfound"
      },
      {
       "expr": "pvc_ceph_pool_num_objects_degraded{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "Pool {{pool}} # Degraded"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage OSD Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSD Disk Space Utilization",
     "type": "gauge",
     "description": "Current disk space utilization of each Ceph OSD.",
     "gridPos": { "h": 16, "w": 9, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pvc_ceph_osd_util{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "OSD {{osd}}"
      }
     ]
    },
    {
     "title": "OSD Disk Space Utilization History",
     "type": "timeseries",
     "description": "Disk space utilization history of each Ceph OSD.",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "pvc_ceph_osd_util{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "OSD {{osd}}"
      }
     ]
    },
    {
     "title": "OSD Disk Space History",
     "type": "timeseries",
     "description": "Disk space history of each Ceph OSD (source metric).",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "pvc_ceph_osd_used{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "OSD {{osd}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS (+ Read/- Write)",
     "type": "timeseries",
     "description": "Total and per-OSD IOPS (I/O operations per second), read and write, in the cluster.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(pvc_ceph_osd_rd_ops{pvc_cluster_id=\"$cluster_id\"})",
       "legendFormat": "Total Read"
      },
      {
       "expr": "sum(pvc_ceph_osd_wr_ops{pvc_cluster_id=\"$cluster_id\"})",
       "legendFormat": "Total Write"
      },
      {
       "expr": "pvc_ceph_osd_rd_ops{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "OSD {{osd}} Read"
      },
      {
       "expr": "pvc_ceph_osd_wr_ops{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "OSD {{osd}} Write"
      }
     ]
    },
    {
     "title": "Data (+ Read/- Write)",
     "type": "timeseries",
     "description": "Total and per-OSD data throughput per second, read and write, in the cluster.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(pvc_ceph_osd_rd_data{pvc_cluster_id=\"$cluster_id\"})",
       "legendFormat": "Total Read"
      },
      {
       "expr": "sum(pvc_ceph_osd_wr_data{pvc_cluster_id=\"$cluster_id\"})",
       "legendFormat": "Total Write"
      },
      {
       "expr": "pvc_ceph_osd_rd_data{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "OSD {{osd}} Read"
      },
      {
       "expr": "pvc_ceph_osd_wr_data{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "OSD {{osd}} Write"
      }
     ]
    },
    {
     "title": "OSD Latency",
     "type": "timeseries",
     "description": "Average operation latency for Ceph OSD daemons in the cluster.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "1000*sum(increase(ceph_osd_op_r_latency_sum{pvc_cluster_id=\"$cluster_id\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_r_latency_count{pvc_cluster_id=\"$cluster_id\"}[1m])),1)",
       "legendFormat": "Read"
      },
      {
       "expr": "1000*sum(increase(ceph_osd_op_w_latency_sum{pvc_cluster_id=\"$cluster_id\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_w_latency_count{pvc_cluster_id=\"$cluster_id\"}[1m])),1)",
       "legendFormat": "Write"
      },
      {
       "expr": "1000*sum(increase(ceph_osd_op_rw_latency_sum{pvc_cluster_id=\"$cluster_id\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_rw_latency_count{pvc_cluster_id=\"$cluster_id\"}[1m])),1)",
       "legendFormat": "Overwrite"
      }
     ]
    },
    {
     "title": "Monitor Latency",
     "type": "timeseries",
     "description": "Average operation latency for Ceph Monitor daemons in the cluster.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "1000*sum(increase(ceph_paxos_refresh_latency_sum{pvc_cluster_id=\"$cluster_id\"}[1m]))/clamp_min(sum(increase(ceph_paxos_refresh_latency_count{pvc_cluster_id=\"$cluster_id\"}[1m])),1)",
       "legendFormat": "Refresh"
      },
      {
       "expr": "1000*sum(increase(ceph_paxos_store_state_latency_sum{pvc_cluster_id=\"$cluster_id\"}[1m]))/clamp_min(sum(increase(ceph_paxos_store_state_latency_count{pvc_cluster_id=\"$cluster_id\"}[1m])),1)",
       "legendFormat": "Store State"
      },
      {
       "expr": "1000*sum(increase(ceph_paxos_commit_latency_sum{pvc_cluster_id=\"$cluster_id\"}[1m]))/clamp_min(sum(increase(ceph_paxos_commit_latency_count{pvc_cluster_id=\"$cluster_id\"}[1m])),1)",
       "legendFormat": "Commit"
      },
      {
       "expr": "1000*sum(increase(ceph_paxos_collect_latency_sum{pvc_cluster_id=\"$cluster_id\"}[1m]))/clamp_min(sum(increase(ceph_paxos_collect_latency_count{pvc_cluster_id=\"$cluster_id\"}[1m])),1)",
       "legendFormat": "Collect"
      },
      {
       "expr": "1000*sum(increase(ceph_paxos_begin_latency_sum{pvc_cluster_id=\"$cluster_id\"}[1m]))/clamp_min(sum(increase(ceph_paxos_begin_latency_count{pvc_cluster_id=\"$cluster_id\"}[1m])),1)",
       "legendFormat": "Begin"
      },
      {
       "expr": "1000*sum(increase(ceph_paxos_new_pn_latency_sum{pvc_cluster_id=\"$cluster_id\"}[1m]))/clamp_min(sum(increase(ceph_paxos_new_pn_latency_count{pvc_cluster_id=\"$cluster_id\"}[1m])),1)",
       "legendFormat": "New PN"
      }
     ]
    }
   ]
  },
  {
   "title": "Zookeeper Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Leader",
     "type": "stat",
     "description": "Current Zookeeper leader node; dynamic based on leader elections.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zk_server_leader{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Version",
     "type": "stat",
     "description": "Current Zookeeper version; all metrics available only with version 3.8.0 and above.",
     "gridPos": { "h": 4, "w": 5, "x": 4, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zk_version{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Quorum Size",
     "type": "stat",
     "description": "Number of Zookeeper nodes in the current Quorum.",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(zk_quorum_size{pvc_cluster_id=\"$cluster_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "description": "Total and alive per-coordinator Zookeeper connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(zk_global_sessions{pvc_cluster_id=\"$cluster_id\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "zk_num_alive_connections{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "Alive {{zk_host}}"
      }
     ]
    },
    {
     "title": "Data Size",
     "type": "stat",
     "description": "Total approximate size of the Zookeeper database.",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(zk_approximate_data_size{pvc_cluster_id=\"$cluster_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Znodes",
     "type": "stat",
     "description": "Total number of znodes (keys) in the Zookeeper database.",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(zk_znode_count{pvc_cluster_id=\"$cluster_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Latency",
     "type": "timeseries",
     "description": "Average Zookeeper latency for each node.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "zk_avg_latency{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "{{zk_host}}"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "description": "Open Zookeeper file descriptors for each node.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "zk_open_file_descriptor_count{pvc_cluster_id=\"$cluster_id\"}",
       "legendFormat": "{{zk_host}}"
      }
     ]
    },
    {
     "title": "Latency Breakdown",
     "type": "timeseries",
     "description": "Average per-operation latency.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(zk_avg_commit_propagation_latency{pvc_cluster_id=\"$cluster_id\"})",
       "legendFormat": "Commit Propagation"
      },
      {
       "expr": "avg(zk_avg_propagation_latency{pvc_cluster_id=\"$cluster_id\"})",
       "legendFormat": "Propagation"
      },
      {
       "expr": "avg(zk_avg_proposal_ack_creation_latency{pvc_cluster_id=\"$cluster_id\"})",
       "legendFormat": "Proposal Ack Creation"
      },
      {
       "expr": "avg(zk_avg_proposal_latency{pvc_cluster_id=\"$cluster_id\"})",
       "legendFormat": "Proposal"
      },
      {
       "expr": "avg(zk_avg_updatelatency{pvc_cluster_id=\"$cluster_id\"})",
       "legendFormat": "Update"
      },
      {
       "expr": "avg(zk_avg_readlatency{pvc_cluster_id=\"$cluster_id\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(zk_avg_readlatency{pvc_cluster_id=\"$cluster_id\"})",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Data Packets (+ Recv/-Send)",
     "type": "timeseries",
     "description": "Zookeeper data packet rate per second for each node.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(zk_packets_received{pvc_cluster_id=\"$cluster_id\"}[1m])",
       "legendFormat": "{{zk_host}} Received"
      },
      {
       "expr": "rate(zk_packets_sent{pvc_cluster_id=\"$cluster_id\"}[1m])",
       "legendFormat": "{{zk_host}} Sent"
      }
     ]
    }
   ]
  }
 ]
}