{
 "title": "PVC VMs",
 "tags": [ "pvc" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Cluster", "query": { "query": "label_values(pvc_cluster_name)" } },
   {
    "name": "cluster_id",
    "query": {
     "query": "label_values({pvc_cluster_name=\"$cluster_name\"},pvc_cluster_id)"
    }
   },
   {
    "name": "vm_name",
    "label": "VM",
    "query": {
     "query": "label_values({pvc_cluster_name=\"$cluster_name\"},vm)"
    }
   }
  ]
 },
 "panels": [
  { "title": "VM Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "Cluster ID as provided by PVC.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_info{pvc_cluster_id=\"$cluster_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM Name",
   "type": "stat",
   "description": "VM name as provided by PVC.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_uuid{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "description": "VM state as provided by PVC.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_state{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UUID",
   "type": "stat",
   "description": "UUID as provided by PVC.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_uuid{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Node",
   "type": "stat",
   "description": "Active node as provided by PVC.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_active_node{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Migrated",
   "type": "stat",
   "description": "If VM is migrated, the last node, or \"No\".",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_migrated{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Autostart",
   "type": "stat",
   "description": "VM autostart flag as provided by PVC.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_autostart{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Description",
   "type": "stat",
   "description": "Description as provided by PVC.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_description{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vCPUs",
   "type": "stat",
   "description": "vCPU count as provided by PVC.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_vcpus{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vCPU Topology",
   "type": "stat",
   "description": "vCPU topology (Sockets/Cores/Threads) as provided by PVC.",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_vcpu_topology{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vRAM",
   "type": "stat",
   "description": "Memory value (MB) as provided by PVC.",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_memory{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Limits",
   "type": "stat",
   "description": "Node limits as provided by PVC.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_node_limit{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Reason",
   "type": "stat",
   "description": "Failure Reason as provided by PVC.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_vm_failed_reason{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU & Memory Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Time",
     "type": "timeseries",
     "description": "CPU time as reported by Libvirt, in milliseconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "pvc_vm_vcpus_cpu_time{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
       "legendFormat": "CPU Time"
      },
      {
       "expr": "pvc_vm_vcpus_user_time{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
       "legendFormat": "User Time"
      },
      {
       "expr": "pvc_vm_vcpus_system_time{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
       "legendFormat": "System Time"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "description": "Memory utilization of VM as reported by libvirt.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "pvc_vm_memory_stats_actual{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
       "legendFormat": "Allocated"
      },
      {
       "expr": "pvc_vm_memory_stats_rss{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
       "legendFormat": "RSS"
      },
      {
       "expr": "pvc_vm_memory_stats_disk_caches{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
       "legendFormat": "Disk Caches"
      }
     ]
    },
    {
     "title": "Memory Page Faults",
     "type": "timeseries",
     "description": "Memory page faults of VM as reported by libvirt.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pvc_vm_memory_stats_major_fault{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
       "legendFormat": "Major"
      },
      {
       "expr": "pvc_vm_memory_stats_minor_fault{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
       "legendFormat": "Minor"
      }
     ]
    },
    {
     "title": "Swap Utilization (+ in/- out)",
     "type": "timeseries",
     "description": "Memory swap utilization of VM as reported by libvirt.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pvc_vm_memory_stats_swap_in{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
       "legendFormat": "In"
      },
      {
       "expr": "pvc_vm_memory_stats_swap_out{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}",
       "legendFormat": "Out"
      }
     ]
    }
   ]
  },
  {
   "title": "NIC Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packets (+ RX/- TX)",
     "type": "timeseries",
     "description": "Packets per second for each NIC of VM as reported by libvirt.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(pvc_vm_network_rd_packets{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}[$__rate_interval])",
       "legendFormat": "VNI {{vni}} RX"
      },
      {
       "expr": "rate(pvc_vm_network_wr_packets{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}[$__rate_interval])",
       "legendFormat": "VNI {{vni}} TX"
      }
     ]
    },
    {
     "title": "Traffic (+ RX/- TX)",
     "type": "timeseries",
     "description": "Bytes per second for each NIC of VM as reported by libvirt.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(pvc_vm_network_rd_bits{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}[$__rate_interval])",
       "legendFormat": "VNI {{vni}} RX"
      },
      {
       "expr": "rate(pvc_vm_network_wr_bits{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}[$__rate_interval])",
       "legendFormat": "VNI {{vni}} TX"
      }
     ]
    },
    {
     "title": "Drops (+ RX/- TX)",
     "type": "timeseries",
     "description": "Drops per second for each NIC of VM as reported by libvirt.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(pvc_vm_network_rd_drops{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}[$__rate_interval])",
       "legendFormat": "VNI {{vni}} RX"
      },
      {
       "expr": "rate(pvc_vm_network_wr_drops{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}[$__rate_interval])",
       "legendFormat": "VNI {{vni}} TX"
      }
     ]
    },
    {
     "title": "Errors (+ RX/- TX)",
     "type": "timeseries",
     "description": "Errors per second for each NIC of VM as reported by libvirt.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(pvc_vm_network_rd_errors{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}[$__rate_interval])",
       "legendFormat": "VNI {{vni}} RX"
      },
      {
       "expr": "rate(pvc_vm_network_wr_errors{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\"}[$__rate_interval])",
       "legendFormat": "VNI {{vni}} TX"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS (+ Read/- Write)",
     "type": "timeseries",
     "description": "I/O requests per second each disk of VM as reported by libvirt; \"sdz\" (metrics disk) excluded explicitly.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(pvc_vm_disk_rd_req{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\", disk!=\"sdz\"}[$__rate_interval])",
       "legendFormat": "Disk {{disk}} Read"
      },
      {
       "expr": "rate(pvc_vm_disk_wr_req{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\", disk!=\"sdz\"}[$__rate_interval])",
       "legendFormat": "Disk {{disk}} Write"
      }
     ]
    },
    {
     "title": "Data (+ Read/- Write)",
     "type": "timeseries",
     "description": "Data bytes per second each disk of VM as reported by libvirt; \"sdz\" (metrics disk) excluded explicitly.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(pvc_vm_disk_rd_bytes{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\", disk!=\"sdz\"}[$__rate_interval])",
       "legendFormat": "Disk {{disk}} Read"
      },
      {
       "expr": "rate(pvc_vm_disk_wr_bytes{pvc_cluster_id=\"$cluster_id\", vm=\"$vm_name\", disk!=\"sdz\"}[$__rate_interval])",
       "legendFormat": "Disk {{disk}} Write"
      }
     ]
    }
   ]
  }
 ]
}