#!/usr/bin/env bash

pushd $( git rev-parse --show-toplevel ) &>/dev/null

ex=0

./prepare
if [[ $? -ne 0 ]]; then
    echo "Aborting commit due to formatting or linting errors."
    ex=1
fi

echo
popd &>/dev/null
exit $ex
