#!/bin/bash

# Apply PVC database migrations
# Part of the Parallel Virtual Cluster (PVC) system

export PVC_CONFIG_FILE="/etc/pvc/pvcapid.yaml"

if [[ ! -f ${PVC_CONFIG_FILE} ]]; then
    echo "Create a configuration file at ${PVC_CONFIG_FILE} before upgrading the database."
    exit 1
fi

pushd /usr/share/pvc

case "$( cat /etc/debian_version )" in
    10.*|11.*)
        # Debian 10 & 11
        ./pvcapid-manage_legacy.py db upgrade
    ;;
    *)
        # Debian 12+
        flask --app ./pvcapid-manage_flask.py db upgrade
    ;;
esac

popd
