#!/bin/bash

# Apply PVC database migrations
# Part of the Parallel Virtual Cluster (PVC) system

PVC_CONFIG_FILE="/etc/pvc/pvcapid.yaml"
PVC_SHARE_DIR="/usr/share/pvc"

if [[ ! -f ${PVC_CONFIG_FILE} ]]; then
    echo "Create a configuration file at ${PVC_CONFIG_FILE} before upgrading the database."
    exit 1
fi

pushd ${PVC_SHARE_DIR}
./pvcapid-manage.py db migrate
./pvcapid-manage.py db upgrade
popd
