#!/bin/bash

# Apply PVC database migrations
# Part of the Parallel Virtual Cluster (PVC) system

export PVC_CONFIG_FILE="/etc/pvc/pvc.conf"

if [[ ! -f ${PVC_CONFIG_FILE} ]]; then
    echo "Create a configuration file at ${PVC_CONFIG_FILE} before upgrading the database."
    exit 1
fi

pushd /usr/share/pvc

export FLASK_APP=./pvcapid-manage-flask.py
flask db upgrade

popd
